antora:
  extensions:
    - ./lib/my-extension.js
site:
  title: InferenceQL
  start_page: query::iql-strict.adoc
content:
  sources:
    - url: https://github.com/InferenceQL/inferenceql.query
      branches: zane/antora
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
