antora:
  extensions:
    - ./lib/my-extension.js
site:
  title: InferenceQL
  start_page: start-page::start-page.adoc
content:
  sources:
  - url: https://github.com/OpenIQL/openiql.github.io
    branches: ulli/document-automodeling
    start_path: landing-page
  - url: https://github.com/OpenIQL/inferenceql.query
    branches: ulli/antora
    start_path: docs
  - url: /home/ulli/git_repos/inferenceql.auto-modeling/
    branches: ulli/docs
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
